/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  MathSidebar: [
    'math/linear-algebra-1',
    'math/linear-algebra-2',
    'math/linear-algebra-3',
    'math/linear-algebra-4',
  ],
  // But you can create a sidebar manually
  CSTheorySidebar: [
    {
      type: 'category',
      label: '算法与数据结构',
      link: {
        type: 'generated-index',
        title: '算法与数据结构',
        description: '算法和数据结构是整个计算机世界的基石之一，也是程序员的基本功。',
        slug: '/category/algorithm',
        keywords: ['algorithm'],
      },
      items: [
        'cs-theory/algorithm/sort'
      ],
    },
  ],

  CSPracticeSidebar: [
    // {
    //   type: 'category',
    //   label: '编程语言',
    //   link: {
    //     type: 'generated-index',
    //     title: '编程语言',
    //     description: '编程语言是程序员与计算机沟通的桥梁。',
    //     slug: '/category/programming-languages',
    //     keywords: ['guides'],
    //   },
    //   items: ['tutorial-basics/create-a-document'],
    // },
    {
      type: 'category',
      label: '开发与运维',
      link: {
        type: 'generated-index',
        title: '开发与运维',
        description: 'todo',
        slug: '/category/devops',
        keywords: ['devops'],
      },
      items: [
        {
          type: 'category',
          label: '编辑器与IDE',
          link: {
            type: 'generated-index',
            title: '编辑器与IDE',
            description: 'todo ',
            slug: '/category/devops/editor-ide',
            keywords: ['editor'],
          },
          items: [
            'cs-practice/devops/vim'
          ],
        },
        {
          type: 'category',
          label: '版本控制',
          link: {
            type: 'generated-index',
            title: '版本控制',
            description: 'todo ',
            slug: '/category/devops/version-control',
            keywords: ['version control', 'git'],
          },
          items: [
            'cs-practice/version-control/git'
          ],
        },
      ],
    },
  ],
};

module.exports = sidebars;
